name: Lifestyle Advisor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Install SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        if [ -f "keypair.pem" ]; then chmod 600 "keypair.pem"; fi

    - name: Debugging
      run: |
        ls -la
        pwd
        git remote -v

    - name: Update code on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-100-24-47-104.compute-1.amazonaws.com
        port: 22
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          git pull origin main
          
