name: Lifestyle Advisor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Install SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        chmod 600 "keypair.pem"

    - name: Update code on EC2
      run: |
        ssh -i "keypair.pem" ubuntu@ec2-100-24-47-104.compute-1.amazonaws.com "cd /lifestyle && git pull origin main"
